# Generated by Django 6.0 on 2026-01-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarymap',
            name='map',
        ),
        migrations.AddField(
            model_name='librarymap',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='librarymap',
            name='lib_code',
            field=models.CharField(default='unknown', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='librarymap',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='librarymap',
            name='name',
            field=models.CharField(default='unknown library', max_length=100),
        ),
    ]
